# Generated by Django 5.2.8 on 2025-11-12 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('location', models.CharField(blank=True, max_length=30)),
                ('birth_date', models.DateField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('security_question_1', models.CharField(choices=[('What was the name of your first pet?', 'What was the name of your first pet?'), ("What is your mother's maiden name?", "What is your mother's maiden name?"), ('What city were you born in?', 'What city were you born in?'), ('What was your high school mascot?', 'What was your high school mascot?'), ('What is the name of your favorite childhood friend?', 'What is the name of your favorite childhood friend?'), ('What was the make of your first car?', 'What was the make of your first car?'), ('What is your favorite book?', 'What is your favorite book?'), ('What is your favorite movie?', 'What is your favorite movie?')], max_length=200)),
                ('security_answer_1', models.CharField(max_length=100)),
                ('security_question_2', models.CharField(choices=[('What was the name of your first pet?', 'What was the name of your first pet?'), ("What is your mother's maiden name?", "What is your mother's maiden name?"), ('What city were you born in?', 'What city were you born in?'), ('What was your high school mascot?', 'What was your high school mascot?'), ('What is the name of your favorite childhood friend?', 'What is the name of your favorite childhood friend?'), ('What was the make of your first car?', 'What was the make of your first car?'), ('What is your favorite book?', 'What is your favorite book?'), ('What is your favorite movie?', 'What is your favorite movie?')], max_length=200)),
                ('security_answer_2', models.CharField(max_length=100)),
                ('security_question_3', models.CharField(choices=[('What was the name of your first pet?', 'What was the name of your first pet?'), ("What is your mother's maiden name?", "What is your mother's maiden name?"), ('What city were you born in?', 'What city were you born in?'), ('What was your high school mascot?', 'What was your high school mascot?'), ('What is the name of your favorite childhood friend?', 'What is the name of your favorite childhood friend?'), ('What was the make of your first car?', 'What was the make of your first car?'), ('What is your favorite book?', 'What is your favorite book?'), ('What is your favorite movie?', 'What is your favorite movie?')], max_length=200)),
                ('security_answer_3', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
